twig:
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"
        classService: "@App\\Class\\Cart"
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
